spring.application.name=payment

# MySQL connection (Aiven Cloud)
spring.datasource.url=jdbc:mysql://mysql-92bbf9f-chauhanbibek989-5bac.i.aivencloud.com:16064/defaultdb?sslMode=REQUIRED
spring.datasource.username=avnadmin
# PLEASE SET 'DB_PASSWORD' IN YOUR ENVIRONMENT VARIABLES
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Hibernate ? update creates/alters tables from @Entity classes automatically
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# JWT
jwt.secret=MySuperSecretKeyThatIsAtLeast256BitsLongForHS256Algorithm
jwt.expiration=86400000

# CORS ? allow React dev server
cors.allowed-origin=http://localhost:5173

